export const ROOT = "";
export const LOGIN_URL = `${ROOT}/user/login`;//登录
export const REGISTE_URL = `${ROOT}/user/register`;//注册
export const CHANGEPASS_URL = `${ROOT}/user/changePassword`;//修改密码
export const GET_USERDATA_URL = `${ROOT}/user/userInfo`;//获取用户个人信息
export const CHANGE_USER_URL = `${ROOT}/user/updateUserInfo`;//修改用户个人信息
export const FORGRT =`${ROOT}/user/forceChangePassword`;//忘记密码
export const GETPHONE =`${ROOT}/user/myPhone`;//获取手机号
export const GETALLARTICLE =`${ROOT}/article/allArticles`;//获取所有心情
export const GETMYYARTICLE =`${ROOT}/article/recentArticles`;//获取我的心情
export const UPARTICLE =`${ROOT}/article/addArticle`;//上传文章
export const GETALLSOUL =`${ROOT}/push/allChickenSouls`;//获取所有鸡汤
export const GETALLMUSIC =`${ROOT}/push/allPushMusics`;//获取所有歌曲
export const UPIMAGE =`${ROOT}/article/uploadImage`;//上传图片
export const DELETEMY =`${ROOT}/article/deleteArticle`;//删除心情
export const EDITEMY =`${ROOT}/article/updateArticle`;//编辑心情
export const AGREE =`${ROOT}/article/likeArticle`;//点赞
export const DISAGREE =`${ROOT}/article/cancelLikeArticle`;// 取消点赞
export const MAKECOMMEMT =`${ROOT}/comment/addComment`;// 评论
export const GETCOMMEMT =`${ROOT}/comment/articleComments`;// 获取评论
export const CHOOSE =`${ROOT}/article/filterArticles`;// 筛选心情
export const SEARCH =`${ROOT}/article/searchArticles`;// 搜索心情
export const GETALLLIKEARTICLE =`${ROOT}/user/likeArticles`;//获取所有点赞过心情
export const GETARTICLEDETAIL =`${ROOT}/article/article`;//获取文章内容
export const HASLIKE =`${ROOT}/user/likeArticles`;//获取文章是否点赞